In [1]:
import pandas as pd
movie_info = pd.read_csv(r"C:\Users\muthu\Downloads\Movie Interests.csv")

In [2]:
movie_info

    Age  Gender   Interest
0     8       1  Animation
1    11       1  Animation
2    12       1  Animation
3    16       1     Action
4    18       1     Action
5    19       1     Action
6    23       1      Drama
7    26       1      Drama
8    27       1      Drama
9     7       0  Animation
10    9       0  Animation
11   10       0  Animation
12   26       0     Action
13   27       0     Action
14   30       0     Action
15   31       0      Drama
16   34       0      Drama
17   35       0      Drama

In [3]:
input_dataset = movie_info.drop(columns=['Interest'])

In [4]:
input_dataset

    Age  Gender
0     8       1
1    11       1
2    12       1
3    16       1
4    18       1
5    19       1
6    23       1
7    26       1
8    27       1
9     7       0
10    9       0
11   10       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [5]:
output_dataset = movie_info['Interest']

In [6]:
output_dataset

0     Animation
1     Animation
2     Animation
3        Action
4        Action
5        Action
6         Drama
7         Drama
8         Drama
9     Animation
10    Animation
11    Animation
12       Action
13       Action
14       Action
15        Drama
16        Drama
17        Drama
Name: Interest, dtype: object

In [7]:
from sklearn.tree import DecisionTreeClassifier
movie_model = DecisionTreeClassifier()
movie_model.fit(input_dataset,output_dataset)
movie_interset= movie_model.predict([[9,2],[35,0]])

C:\Users\muthu\anaconda3\envs\etl_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [8]:
movie_interset

array(['Animation', 'Drama'], dtype=object)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
movie_model = KNeighborsClassifier(n_neighbors=3)
movie_model.fit(input_dataset, output_dataset)
movie_interest = movie_model.predict([[9, 2], [35, 0]])

C:\Users\muthu\anaconda3\envs\etl_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [10]:
movie_interest

array(['Animation', 'Drama'], dtype=object)

In [11]:
from sklearn.svm import SVC
movie_model = SVC()
movie_model.fit(input_dataset, output_dataset)
movie_interest = movie_model.predict([[9, 2], [35, 0]])

C:\Users\muthu\anaconda3\envs\etl_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [12]:
movie_interest

array(['Animation', 'Drama'], dtype=object)

In [32]:
import pickle
# Save your trained model
pickle.dump(movie_model, open('movie_model.pkl', 'wb'))

In [33]:
model1=pickle.load(open('movie_model.pkl','rb'))
print(model1.predict([[9,1],[33,0]]))

['Animation' 'Drama']

C:\Users\muthu\anaconda3\envs\etl_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [34]:
movie_model

SVC()